apiVersion: apps/v1
kind: Deployment
metadata:
  name: population-deployment
  labels:
    app: population
spec:
  replicas: 1
  selector:
    matchLabels:
      app: population
  template:
    metadata:
      labels:
        app: population
    spec:
      containers:
      - name: population
        image: registry.local:5000/population-service
        volumeMounts:
        - name: ssl
          mountPath: /etc/config
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "250m"
            memory: "512Mi"
          requests:
            memory: "256Mi"
        env:
          - name: PORT
            value: "80"
          - name: SB_URL
            value: "rabbitmq.infra"
          - name: SB_PWD
            value: "Secr3t"
          - name: SB_PORT
            value: "5672"
          - name: REGISTER_AS
            value: "population.backend"
        securityContext:
          privileged: true
      # imagePullSecrets:
      # - name: regcred
      volumes:
      - name: ssl
        secret:
          secretName: ssl-key-cert