apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  labels:
    app: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: registry.local:5000/weather-service
        volumeMounts:
        - name: ssl
          mountPath: /etc/config
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "250m"
            memory: "512Mi"
          requests:
            memory: "256Mi"
        env:
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "80"
          - name: SB_URL
            value: "rabbitmq.infra"
          - name: SB_PWD
            value: "Secr3t"
          - name: SB_PORT
            value: "5672"
          - name: APP_ID
            value: 5e1faa4ff336e703c364487b3ec7f325
          - name: REGISTER_AS
            value: "weather.backend"
        securityContext:
          privileged: true
      # imagePullSecrets:
      # - name: regcred
      volumes:
      - name: ssl
        secret:
          secretName: ssl-key-cert