trigger:
  branches:
    include:
    - develop
    - master
  paths: 
    include:
    - api-gateway/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    submodules: true
  - task: Docker@2
    inputs:
      containerRegistry: $(RegistryConnection)
      repository: $(Repository)
      Dockerfile: 'api-gateway/Dockerfile'
      tags: |
        0.0.$(Build.BuildId)
        latest