trigger:
  branches:
    include:
    - develop
    - master
  paths: 
    include:
    - api-gateway/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Build'
    jobs:
      - job: 'BuildDockerImage'
        displayName: 'Build docker image'
        steps:
        - checkout: self
          submodules: true
        - task: Docker@2
          inputs:
            containerRegistry: $(RegistryConnection)
            repository: $(Repository)
            command: 'buildAndPush'
            Dockerfile: '**/api-gateway/Dockerfile'
            tags: |
              0.0.$(Build.BuildId)
              latest
  - stage: 'Deploy'
    jobs:
      - job: 'DeployKubernetes'
        displayName: 'Deploy to k8s'
        steps:
        - task: Kubernetes@1
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: $(K8sServiceEndpoint)
            namespace: $(Namespace)
            command: 'set'
            arguments: 'image deployment/api api=$(Repository):0.0.$(Build.BuildId)'
            secretType: 'dockerRegistry'
            containerRegistryType: 'Azure Container Registry'
            outputFormat: 'yaml'
        - task: Kubernetes@1
          condition: and(succeeded(), eq(variables['IsOkteto'], true)) 
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: '$(K8sServiceEndpoint)'
            namespace: '$(Namespace)'
            command: 'delete'
            arguments: 'pod -l app=api'
            secretType: 'dockerRegistry'
            containerRegistryType: 'Azure Container Registry'
            outputFormat: 'yaml'