apiVersion: v1
kind: Service
metadata:
  {{- if not .Values.isOkteto }}
  namespace: {{ .Values.fluentd.namespace }}
  {{ end }}
  name: {{ .Values.fluentd.host }} 
spec:
  ports:
  - name: logging
    targetPort: {{ .Values.fluentd.port }} 
    port: {{ .Values.fluentd.port }} 
  selector:
    app: {{ .Values.fluentd.host }} 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if not .Values.isOkteto }}
  namespace: {{ .Values.fluentd.namespace }}
  {{ end }}
  name: {{ .Values.fluentd.host }} 
  labels:
    app.kubernetes.io/component: {{ .Values.fluentd.host }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.fluentd.host }} 
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.fluentd.host }} 
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: fluentd-volume
          configMap:
            name: fluentd
      {{ include "grpc.initContainers" . }}
      containers:
        - name: fluentd
          image: {{ .Values.fluentd.image }}
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              memory: "100Mi"
          ports:
            - containerPort: {{ .Values.fluentd.port }}
          volumeMounts:
            - name: fluentd-volume
              mountPath: /fluentd/etc/
---
apiVersion: v1
kind: ConfigMap
metadata:
  {{- if not .Values.isOkteto }}
  namespace: {{ .Values.fluentd.namespace }}
  {{ end }}
  name: fluentd
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
    <filter **>
      @type record_transformer
      enable_ruby
      <record>
        timestamp ${ require 'time'; Time.now.utc.iso8601(3) }
      </record>
    </filter>
    <match *.**>
      @type copy
      <store>   
        @type elasticsearch
        host {{ .Values.elastic.host | quote }}
        port {{ .Values.elastic.port }}
        logstash_format true
        logstash_prefix fluentd
        logstash_dateformat %Y%m%d
        include_timestamp true
        time_key_exclude_timestamp false
        time_key timestamp
        time_key_format %Y-%m-%dT%H:%M:%S.%N%z
        include_tag_key true
        type_name access_log
        tag_key @log_name
        flush_interval 1s
      </store>
      <store>
        @type stdout
      </store>
    </match>
        