apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
    <filter **>
      @type record_transformer
      enable_ruby
      <record>
        timestamp ${ require 'time'; Time.now.utc.iso8601(3) }
      </record>
    </filter>
    <match *.**>
      @type copy
      <store>   
        @type elasticsearch
        host {{ .Values.elastic.host | quote }}
        port {{ .Values.elastic.port }}
        {{- if not .Values.elastic.useLocal }}
        user {{ .Values.elastic.user | quote }}
        password {{ .Values.elastic.password | quote }}
        scheme https
        index_name fluentd.${tag}
        {{- end }}
        logstash_format true
        logstash_prefix fluentd
        logstash_dateformat %Y%m%d
        include_timestamp true
        time_key_exclude_timestamp false
        time_key timestamp
        time_key_format %Y-%m-%dT%H:%M:%S.%N%z
        include_tag_key true
        type_name access_log
        tag_key @log_name
        flush_interval 1s
      </store>
      <store>
        @type stdout
      </store>
    </match>