{{- if not .Values.isOkteto }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.pgsql.namespace }}
  name: {{ .Values.pgsql.host }}
spec:
  ports:
  - name: db
    targetPort: {{ .Values.pgsql.port }}
    port: {{ .Values.pgsql.port }}
  selector:
    app: {{ .Values.pgsql.host }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if not .Values.isOkteto }}
  namespace: {{ .Values.pgsql.namespace }}
  {{ end }}
  name: {{ .Values.pgsql.host }}
  labels:
    app.kubernetes.io/component: {{ .Values.pgsql.host }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.pgsql.host }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- if not .Values.isOkteto }}
      namespace: {{ .Values.pgsql.namespace }}
      {{ end }}
      labels:
        app: {{ .Values.pgsql.host }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.pgsql.host }}
          image: {{ .Values.pgsql.image }}
          ports:
          - containerPort: {{ .Values.pgsql.port }}
          resources:
            limits:
              cpu: "50m"
              memory: "500Mi"
            requests:
              memory: "200Mi"
          env:
            - name: POSTGRES_USER
              value: {{ .Values.pgsql.user }}
            - name: POSTGRES_DB
              value: {{ .Values.pgsql.database }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.pgsql.password }}
{{ end }}