apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      external_labels:
        monitor: grpc-monitor
    scrape_configs:
      - job_name: prometheus
        scrape_interval: 5s
        static_configs:
          - targets:
              - 'localhost:9090'
              {{- if .Values.isOkteto }}
              - {{ .Values.apiGateway.host }}:{{ .Values.metricsPort }}
              - {{ .Values.discoveryService.host }}:{{ .Values.metricsPort }}
              - {{ .Values.nearbyCitiesService.host }}:{{ .Values.metricsPort }}
              - {{ .Values.populationService.host }}:{{ .Values.metricsPort }}
              - {{ .Values.weatherService.host }}:{{ .Values.metricsPort }}
              {{ end }}
      {{- if not .Values.isOkteto }}
      - job_name: kubernetes-service-endpoints
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels:
              - __meta_kubernetes_namespace
            action: replace
            target_label: kubernetes_namespace
          - source_labels:
              - __meta_kubernetes_service_name
            action: replace
            target_label: kubernetes_name
      {{ end }}