version: '3.4'

services:
  # population:
  #   build: ../population-service
  #   image: population-service
  #   restart: always
  #   ports: 
  #     - 5011:5011
  #   environment: 
  #     - PORT=5011
  #     - HOST=0.0.0.0
  #     - SB_USER=admin
  #     - SB_URL=rabbitmq
  #     - SB_PWD=Secr3t
  #     - SB_PORT=5672
  #     - REGISTER_AS=localhost
  #     - LOGGER_HOST=fluentd
  #   depends_on: 
  #     - rabbitmq
  # discovery:
  #   build: ../discovery-service
  #   image: discovery-service
  #   restart: always
  #   ports: 
  #     - 5010:80
  #   environment: 
  #     - ServiceBus__Username=admin
  #     - ServiceBus__Host=rabbitmq
  #     - ServiceBus__Password=Secr3t
  #     - ConnectionStrings__Etcd=http://etcd
  #     - Grpc__Host=discovery
  #     - Grpc__Port=80
  #   depends_on: 
  #     - rabbitmq
  #     - etcd
  weather:
    build: ../weather-service
    image: weather-service
    restart: always
    ports: 
      - 5012:5012
    environment: 
      - METRICS_HOST_URL=influxdb
      - METRICS_USERNAME=admin
      - METRICS_PASSWORD=supersecretpassword
      - PORT=5012
      - HOST=0.0.0.0
      - SB_USER=admin
      - SB_URL=rabbitmq
      - SB_PWD=Secr3t
      - SB_PORT=5672
      - OPENWEATHER_APP_ID=5e1faa4ff336e703c364487b3ec7f325
      - REGISTER_AS=localhost
      - LOGGER_HOST=fluentd
      - LOGGER_PORT=24224
    depends_on: 
      - rabbitmq
      - influxdb
  # nearby-cities:
  #   build: ../nearby-cities-service
  #   image: nearby-cities-service
  #   restart: always
  #   ports: 
  #     - 5013:5013
  #   environment: 
  #     - PORT=5013
  #     - HOST=0.0.0.0
  #     - LOGGER_HOST=fluentd
  #     - SB_USER=admin
  #     - SB_URL=rabbitmq
  #     - SB_PWD=Secr3t
  #     - SB_PORT=5672
  #     - REGISTER_AS=localhost
  #   depends_on: 
  #     - rabbitmq
  #     - fluentd
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    restart: always
    ports:
      - 8080:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Secr3t
  etcd:
    image: bitnami/etcd
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
  fluentd:
    build: ../infra/fluentd
    volumes:
      - ../infra/fluentd/conf:/fluentd/etc
    links:
      - "elk"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elk
  elk:
    image: blacktop/elastic-stack:7.8
    ports:
      - 9200:9200
      - 5601:80
  influxdb:
    image: influxdb:alpine
    ports:
      - 8086:8086
    environment:
      - INFLUX_DB=metrics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=secretpassword
  influxdbui:
    image: sillydong/influxdb-ui
    ports:
      - 9091:80
  grafana:
    image: woahbase/alpine-grafana
    ports:
     - 3000:3000
