version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    restart: always
    ports:
      - 8080:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Secr3t
  etcd:
    image: bitnami/etcd
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
  fluentd:
    image: fluentd
    build: ./infra/fluentd
    volumes:
      - ./infra/fluentd/conf:/fluentd/etc
    links:
      - "elk"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elk
  elk:
    image: blacktop/elastic-stack:7.8
    ports:
      - 9200:9200
      - 5601:80
  influxdb:
    image: influxdb:1.7-alpine
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_PASSWORD=password123
  grafana:
    image: grafana/grafana:7.1.3
    ports:
      - 3000:3000
  vault:
    image: vault
    environment:
      VAULT_ADDR: http://localhost:8200
      VAULT_API_ADDR: http://0.0.0.0:8200
      VAULT_LOCAL_CONFIG: >-
        {
          "storage": {
            "file": {
              "path": "/var/vault/file"
            }
          },
          "listener": {
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": true
            }
          },
          "ui": true,
          "max_lease_ttl": "8760h",
          "default_lease_ttl": "8760h",
          "disable_mlock": true
        }
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    command: server & vault operator init
    volumes: 
      - ./infra/vault/data:/var/vault/file