// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DiscoveryServiceClient is the client API for DiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryServiceClient interface {
	GetServiceHandlers(ctx context.Context, in *DiscoverySearchRequest, opts ...grpc.CallOption) (*DiscoverySearchResponse, error)
	RegisterServiceHandlers(ctx context.Context, in *RegisterServiceHandlersRequest, opts ...grpc.CallOption) (*RegisterServiceHandlersResponse, error)
	UnregisterService(ctx context.Context, in *UnregisterServiceRequest, opts ...grpc.CallOption) (*UnregisterServiceResponse, error)
}

type discoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryServiceClient(cc grpc.ClientConnInterface) DiscoveryServiceClient {
	return &discoveryServiceClient{cc}
}

func (c *discoveryServiceClient) GetServiceHandlers(ctx context.Context, in *DiscoverySearchRequest, opts ...grpc.CallOption) (*DiscoverySearchResponse, error) {
	out := new(DiscoverySearchResponse)
	err := c.cc.Invoke(ctx, "/discovery.DiscoveryService/GetServiceHandlers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) RegisterServiceHandlers(ctx context.Context, in *RegisterServiceHandlersRequest, opts ...grpc.CallOption) (*RegisterServiceHandlersResponse, error) {
	out := new(RegisterServiceHandlersResponse)
	err := c.cc.Invoke(ctx, "/discovery.DiscoveryService/RegisterServiceHandlers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) UnregisterService(ctx context.Context, in *UnregisterServiceRequest, opts ...grpc.CallOption) (*UnregisterServiceResponse, error) {
	out := new(UnregisterServiceResponse)
	err := c.cc.Invoke(ctx, "/discovery.DiscoveryService/UnregisterService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServiceServer is the server API for DiscoveryService service.
// All implementations must embed UnimplementedDiscoveryServiceServer
// for forward compatibility
type DiscoveryServiceServer interface {
	GetServiceHandlers(context.Context, *DiscoverySearchRequest) (*DiscoverySearchResponse, error)
	RegisterServiceHandlers(context.Context, *RegisterServiceHandlersRequest) (*RegisterServiceHandlersResponse, error)
	UnregisterService(context.Context, *UnregisterServiceRequest) (*UnregisterServiceResponse, error)
	mustEmbedUnimplementedDiscoveryServiceServer()
}

// UnimplementedDiscoveryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDiscoveryServiceServer struct {
}

func (UnimplementedDiscoveryServiceServer) GetServiceHandlers(context.Context, *DiscoverySearchRequest) (*DiscoverySearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceHandlers not implemented")
}
func (UnimplementedDiscoveryServiceServer) RegisterServiceHandlers(context.Context, *RegisterServiceHandlersRequest) (*RegisterServiceHandlersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterServiceHandlers not implemented")
}
func (UnimplementedDiscoveryServiceServer) UnregisterService(context.Context, *UnregisterServiceRequest) (*UnregisterServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterService not implemented")
}
func (UnimplementedDiscoveryServiceServer) mustEmbedUnimplementedDiscoveryServiceServer() {}

// UnsafeDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServiceServer will
// result in compilation errors.
type UnsafeDiscoveryServiceServer interface {
	mustEmbedUnimplementedDiscoveryServiceServer()
}

func RegisterDiscoveryServiceServer(s grpc.ServiceRegistrar, srv DiscoveryServiceServer) {
	s.RegisterService(&DiscoveryService_ServiceDesc, srv)
}

func _DiscoveryService_GetServiceHandlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverySearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).GetServiceHandlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discovery.DiscoveryService/GetServiceHandlers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).GetServiceHandlers(ctx, req.(*DiscoverySearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_RegisterServiceHandlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceHandlersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).RegisterServiceHandlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discovery.DiscoveryService/RegisterServiceHandlers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).RegisterServiceHandlers(ctx, req.(*RegisterServiceHandlersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_UnregisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).UnregisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discovery.DiscoveryService/UnregisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).UnregisterService(ctx, req.(*UnregisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoveryService_ServiceDesc is the grpc.ServiceDesc for DiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discovery.DiscoveryService",
	HandlerType: (*DiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceHandlers",
			Handler:    _DiscoveryService_GetServiceHandlers_Handler,
		},
		{
			MethodName: "RegisterServiceHandlers",
			Handler:    _DiscoveryService_RegisterServiceHandlers_Handler,
		},
		{
			MethodName: "UnregisterService",
			Handler:    _DiscoveryService_UnregisterService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contract/discovery.proto",
}
