apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - name: http
    targetPort: 15672
    port: 80
  - name: ampq
    targetPort: 5672
    port: 5672
  selector:
    app: rabbitmq