# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: healthcheck.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='healthcheck.proto',
  package='healthcheck',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11healthcheck.proto\x12\x0bhealthcheck\"\x07\n\x05\x45mpty\" \n\x0cPingResponse\x12\x10\n\x08response\x18\x01 \x01(\t2R\n\x12HealthCheckService\x12<\n\tGetStatus\x12\x12.healthcheck.Empty\x1a\x19.healthcheck.PingResponse\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='healthcheck.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=41,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='healthcheck.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='healthcheck.PingResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'healthcheck_pb2'
  # @@protoc_insertion_point(class_scope:healthcheck.Empty)
  })
_sym_db.RegisterMessage(Empty)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'healthcheck_pb2'
  # @@protoc_insertion_point(class_scope:healthcheck.PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)



_HEALTHCHECKSERVICE = _descriptor.ServiceDescriptor(
  name='HealthCheckService',
  full_name='healthcheck.HealthCheckService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=77,
  serialized_end=159,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStatus',
    full_name='healthcheck.HealthCheckService.GetStatus',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_PINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEALTHCHECKSERVICE)

DESCRIPTOR.services_by_name['HealthCheckService'] = _HEALTHCHECKSERVICE

# @@protoc_insertion_point(module_scope)
