apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: registry.local:5000/api-gateway
        volumeMounts:
        - name: ssl
          mountPath: /etc/config
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            memory: "256Mi"
        env:
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: ConnectionStrings__Etcd
            value: "http://etcd.infra"
        securityContext:
          privileged: true
      # imagePullSecrets:
      # - name: regcred
      volumes:
      - name: ssl
        secret:
          secretName: ssl-key-cert