trigger:
  branches:
    include:
    - develop
    - master
  paths: 
    include:
    - discovery-service/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Build'
    jobs:
      - job: 'BuildDockerImage'
        displayName: 'Build docker image'
        steps:
        - checkout: self
          submodules: true
        - task: Docker@2
          inputs:
            containerRegistry: $(RegistryConnection)
            repository: $(Repository)
            command: 'buildAndPush'
            Dockerfile: '**/discovery-service/Dockerfile'
            tags: |
              0.0.$(Build.BuildId)
              latest
  - stage: 'Deploy'
    jobs:
      - job: 'DeployKubernetes'
        displayName: 'Deploy to k8s'
        steps:
        - task: Kubernetes@1
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: $(K8sServiceEndpoint)
            namespace: $(Namespace)
            command: 'set'
            arguments: 'image deployment/discovery discovery=$(Repository):0.0.$(Build.BuildId)'
            secretType: 'dockerRegistry'
            containerRegistryType: 'Azure Container Registry'
        - task: Kubernetes@1
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: '$(K8sServiceEndpoint)'
            namespace: '$(Namespace)'
            arguments: 'rollout restart deployment/discovery'
            secretType: 'dockerRegistry'
            containerRegistryType: 'Azure Container Registry'