FROM golang:1.17-bullseye

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

RUN GRPC_HEALTH_PROBE_VERSION=v0.4.11 && \
    wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /bin/grpc_health_probe 

COPY . .
RUN go test ./...

RUN go build ./agent/cmd/main.go 

CMD for i in {1..5}; do grpc_health_probe -addr=$SERVICE_URL && break || sleep 15; done \
&& ./main --master-node $MASTER_NODE --service $SERVICE_NAME --service-url $SERVICE_URL --log-path $LOG_PATH