FROM golang:1.17-bullseye

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN go build ./agent/cmd/main.go 

CMD ./main --master-node $MASTER_NODE --service $SERVICE_NAME --service-url $SERVICE_URL --log-path $LOG_PATH