FROM golang:1.17-bullseye

ENV PORT=50004

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN go build ./master/cmd/main.go 

CMD cp -n ./master/adapter/database/sqlite.db $DB_PATH \
    && ./main --port $PORT --log-path $LOG_PATH --db-path $DB_PATH