apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  labels:
    app: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
      - name: discovery
        image: registry.local:5000/discovery-service
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "100m"
            memory: "200Mi"
          requests:
            memory: "100Mi"
        env:
          - name: ServiceBus__Username
            value: "admin"
          - name: ServiceBus__Host
            value: "rabbitmq.infra"
          - name: ServiceBus__Password
            value: "Secr3t"
          - name: ConnectionStrings__Etcd
            value: "http://etcd.infra"
        securityContext:
          privileged: true
      # imagePullSecrets:
      # - name: regcred