apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk-deployment
  labels:
    app: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk
  template:
    metadata: 
      labels:
        app: elk
    spec:
      containers:
      - name: elk
        image: sebp/elk:761
        ports:
        - containerPort: 5601
        - containerPort: 9200
        - containerPort: 5044
        resources:
          limits:
            cpu: "500m"
            memory: "1000Mi"
          requests:
            cpu: "200m"
            memory: "200Mi"
        securityContext:
          privileged: true