apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-deployment
  labels:
    app: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: bitnami/etcd
        ports:
        - containerPort: 2379
        - containerPort: 2380
        resources:
          limits:
            cpu: "50m"
            memory: "100Mi"
          requests:
            memory: "100Mi"
        env:
          - name: ALLOW_NONE_AUTHENTICATION
            value: "yes"
          - name: ETCD_ADVERTISE_CLIENT_URLS
            value: "http://etcd.infra:2379"
        securityContext:
          privileged: true