apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8-management-alpine
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            cpu: "200m"
            memory: "200Mi"
          requests:
            memory: "200Mi"
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: "admin"
          - name: RABBITMQ_DEFAULT_PASS
            value: "Secr3t"
          - name: RABBITMQ_VM_MEMORY_HIGH_WATERMARK
            value: 256MiB
        securityContext:
          privileged: true

      