apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend
  annotations:
    ingress.kubernetes.io/protocol: h2c
    ingress.kubernetes.io/ssl-passthrough: "true"
    kubernetes.io/ingress.class: traefik
    traefik.protocol: h2c
spec:
  rules:
  - host: population.backend.localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: population
          servicePort: http
  - host: wheater.backend.localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: weather
          servicePort: http
  - host: nearby-cities.backend.localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: nearby-cities
          servicePort: http