apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiGateway.host }} 
  labels:
    app.kubernetes.io/component: {{ .Values.apiGateway.host }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.apiGateway.host }} 
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.apiGateway.host }} 
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{ include "grpc.initContainers" . }}
      containers:
      - name: {{ .Values.apiGateway.host }} 
        image: {{ .Values.apiGateway.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.apiGateway.port }} 
        resources:
          limits:
            cpu: "300m"
            memory: "400Mi"
          requests:
            cpu: "200m"
            memory: "200Mi"
        env:
          - name: ASPNETCORE_URLS
            value: "http://+:{{ .Values.apiGateway.port }}"
          - name: DiscoveryService__Url
            value: "{{ .Values.discoveryService.host }}:{{ .Values.discoveryService.port }}"
          - name: Logging__Host
            value: {{ .Values.fluentd.host | quote }}
          - name: Logging__Port
            value: {{ .Values.fluentd.port | quote }}
          - name: Logging__Tag
            value: {{ .Values.apiGateway.host | quote }}
          - name: Metrics__Port
            value: "3000"