apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.discoveryService.host }} 
spec:
  ports:
  - name: grpc
    targetPort: {{ .Values.discoveryService.port }} 
    port: {{ .Values.discoveryService.port }} 
  {{ include "grpc.metrics" .}}
  selector:
    app.kubernetes.io/name: discovery
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiGateway.host }} 
  {{ if .Values.isOkteto }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
  {{ end }}
spec:
  ports:
  - name: http
    targetPort: {{ .Values.apiGateway.port }} 
    port: {{ .Values.apiGateway.port }} 
  {{ include "grpc.metrics" .}}
  selector:
    app.kubernetes.io/name: {{ .Values.apiGateway.host }} 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.populationService.host }} 
spec:
  ports:
  - name: grpc
    targetPort: {{ .Values.populationService.port }} 
    port: {{ .Values.populationService.port }} 
  {{ include "grpc.metrics" .}}
  selector:
    app.kubernetes.io/name: {{ .Values.populationService.host }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nearbyCitiesService.host }} 
spec:
  ports:
  - name: grpc
    targetPort: {{ .Values.nearbyCitiesService.port }} 
    port: {{ .Values.nearbyCitiesService.port }} 
  {{ include "grpc.metrics" .}}
  selector:
    app.kubernetes.io/name: {{ .Values.nearbyCitiesService.host }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.weatherService.host }} 
spec:
  ports:
  - name: grpc
    targetPort: {{ .Values.weatherService.port }} 
    port: {{ .Values.weatherService.port }} 
  {{ include "grpc.metrics" .}}
  selector:
    app.kubernetes.io/name: {{ .Values.weatherService.host }}
---