apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
  labels:
    app.kubernetes.io/component: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: discovery
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: discovery
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      {{ include "grpc.initContainers" . }}
      containers:
      - name: discovery
        image: {{ .Values.discoveryService.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.discoveryService.port }} 
        resources:
          limits:
            cpu: "300m"
            memory: "400Mi"
          requests:
            cpu: "200m"
            memory: "200Mi"
        env:
          - name: ServiceBus__Username
            value: {{ .Values.rabbitmq.user | quote }}
          - name: ServiceBus__Host
            value: {{ .Values.rabbitmq.host | quote }}
          - name: ServiceBus__Password
            value: {{ .Values.rabbitmq.password | quote }}
          - name: ConnectionStrings__Etcd
            value: {{ .Values.etcd.host | quote }}
          - name: Grpc__Host
            value: "0.0.0.0"
          - name: Grpc__Port
            value: {{ .Values.discoveryService.port | quote }}
          - name: Logging__Host
            value: {{ .Values.fluentd.host | quote }}
          - name: Logging__Port
            value: {{ .Values.fluentd.port | quote }}
          - name: Logging__Tag
            value: "discovery"
          - name: Metrics__Port
            value: "3000"