apiVersion: v1
kind: Service
metadata:
  name: kibana
  annotations:
      dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app.kubernetes.io/name: infra
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elastic.host }}
spec:
  ports:
  - name: {{ .Values.elastic.host }}
    targetPort: 9200
    port: 9200
  selector:
    app.kubernetes.io/name: infra
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - name: http
    targetPort: 15672
    port: 15672
  selector:
    app.kubernetes.io/name: infra