apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra
  labels:
    app.kubernetes.io/component: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: infra
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: infra
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: fluentd-volume
          configMap:
            name: fluentd
      containers:
        - name: fluentd
          image: {{ .Values.fluentd.image }}
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              memory: "100Mi"
          env:
            - name: ELASTIC_HOST
              value: {{ .Values.elastic.host | quote }}
            - name: ELASTIC_PORT
              value: {{ .Values.elastic.port | quote }}
          ports:
            - containerPort: 24224
          volumeMounts:
            - name: fluentd-volume
              mountPath: /fluentd/etc/
        - name: etcd
          image: {{ .Values.etcd.image }}
          ports:
          - containerPort: 2379
          - containerPort: 2380
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              memory: "100Mi"
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://etcd:2379"
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          ports:
          - containerPort: 5672
          - containerPort: 15672
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
            requests:
              memory: "200Mi"
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.user | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.password | quote }}
            - name: RABBITMQ_VM_MEMORY_HIGH_WATERMARK
              value: "256MiB"
        - name: elk
          image: {{ .Values.elastic.image }}
          ports:
          - containerPort: 80
          - containerPort: 9200
          resources:
            limits:
              cpu: "500m"
              memory: "2000Mi"
            requests:
              cpu: "500m"
              memory: "1500Mi"