scrape_configs:
- job_name: scrape_services
  scrape_interval: 5s
  metrics_path: /metrics
  static_configs:
  - targets:
    - population:3000
    - weather:3000
    - nearby-cities:3000
    - api-gateway:3000
    - discovery:3000